# Generated by Django 5.1.6 on 2025-02-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_options_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=200, null=True)),
                ('shop_address', models.TextField(blank=True, null=True)),
                ('shop_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('shop_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='shop_logo/')),
                ('working_hours', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
